export const AGREEMENT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_ACCEPTANCE: 'PENDING_ACCEPTANCE',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
} as const;

export const AGREEMENT_TYPE = {
  SIMPLE: 'SIMPLE',
  WITH_GUARANTEE: 'WITH_GUARANTEE',
} as const;

export const AGREEMENT_EVENT_TYPE = {
  CREATED: 'CREATED',
  SENT: 'SENT',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  PAYMENT_REQUESTED: 'PAYMENT_REQUESTED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  COMPLETED: 'COMPLETED',
  DISPUTED: 'DISPUTED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
  BLOCKCHAIN_RECORDED: 'BLOCKCHAIN_RECORDED',
} as const;

export type AgreementStatus = (typeof AGREEMENT_STATUS)[keyof typeof AGREEMENT_STATUS];
export type AgreementType = (typeof AGREEMENT_TYPE)[keyof typeof AGREEMENT_TYPE];
export type AgreementEventType = (typeof AGREEMENT_EVENT_TYPE)[keyof typeof AGREEMENT_EVENT_TYPE];
